<?php

return [
    1 => [
        'title' => 'Bâtiment R+5 à Angré Djorobité : une réalisation clé',
        'excerpt' => "Retour sur un chantier d'envergure mené par nos équipes, du terrassement jusqu'aux finitions, dans le respect des délais et des normes de construction.",
        'tag' => 'BTP, Construction',
        'image' => 'single_blog_1.png',
        'intro' => "Ce chantier illustre parfaitement le savoir-faire de SYS-Technologies Group en matière de génie civil et de construction de bâtiments à plusieurs niveaux, mené du terrassement jusqu'aux finitions.",
        'body' => "Notre équipe technique a procédé à une étude et un dimensionnement rigoureux avant l'exécution des travaux, afin d'anticiper les contraintes du terrain et garantir la solidité de l'ouvrage sur le long terme. Les travaux ont couvert l'ensemble des lots : terrassement, fondations, gros œuvre, plomberie sanitaire et assainissement, faux plafond, carrelage et peinture. Le résultat est un bâtiment livré dans les délais convenus, conforme aux exigences techniques et de sécurité.",
        'prev' => 5,
        'next' => 2,
    ],
    2 => [
        'title' => "30 Villas Duplex à Yopougon-Songon : un projet d'envergure",
        'excerpt' => "Un programme immobilier ambitieux illustrant notre capacité à gérer des chantiers de grande envergure, de l'étude technique à la livraison.",
        'tag' => 'BTP, Construction',
        'image' => 'single_blog_2.png',
        'intro' => "Ce programme immobilier de 30 villas duplex à Yopougon-Songon illustre notre capacité à gérer des chantiers de grande ampleur, tout en maintenant une qualité homogène sur l'ensemble des unités.",
        'body' => "De l'étude technique au dimensionnement, en passant par le gros œuvre et les finitions, chaque villa a bénéficié du même niveau d'exigence. Ce type de projet nécessite une coordination précise entre les équipes de terrassement, de fondation et de second œuvre pour tenir les délais sur un programme de cette taille.",
        'prev' => 1,
        'next' => 3,
    ],
    3 => [
        'title' => 'Immeuble R+3 à Bingerville : travaux de fondation achevés',
        'excerpt' => "Les fondations de cet immeuble ont été réalisées avec rigueur par nos équipes techniques, posant les bases d'une structure durable.",
        'tag' => 'BTP, Construction',
        'image' => 'single_blog_3.png',
        'intro' => "Les fondations de cet immeuble R+3 à Bingerville ont été réalisées avec rigueur par nos équipes techniques, posant les bases d'une structure durable.",
        'body' => "Une étude technique et un dimensionnement précis ont précédé l'exécution des travaux de fondation, étape déterminante pour la stabilité de l'ensemble de l'ouvrage. Ce chantier illustre l'attention portée par SYS-Technologies Group aux fondamentaux techniques, avant même que la structure ne s'élève.",
        'prev' => 2,
        'next' => 4,
    ],
    4 => [
        'title' => "Piscine à Jacqueville : un chantier vers l'achèvement",
        'excerpt' => "Un projet technique combinant génie civil et étanchéité, mené en parallèle de nos autres chantiers résidentiels.",
        'tag' => 'BTP, Construction',
        'image' => 'single_blog_4.png',
        'intro' => "Cette piscine à Jacqueville, actuellement en cours d'achèvement, combine génie civil et étanchéité, menée avec la même rigueur que nos chantiers de construction résidentielle.",
        'body' => "Le coulage du bassin et la mise en œuvre de l'étanchéité demandent une précision technique particulière, dans un environnement en bord de lagune. Ce projet illustre la diversité des compétences mobilisées par nos équipes au-delà du bâtiment résidentiel classique.",
        'prev' => 3,
        'next' => 5,
    ],
    5 => [
        'title' => 'SYS-Technologies Group renforce son expertise en énergies renouvelables',
        'excerpt' => "Photovoltaïque, pompage solaire, optimisation énergétique : notre équipe technique développe son savoir-faire sur les solutions d'énergie renouvelable.",
        'tag' => 'Énergie, Technologies',
        'image' => 'single_blog_5.png',
        'intro' => "Au-delà du BTP, SYS-Technologies Group développe son expertise sur les solutions d'énergie renouvelable : systèmes photovoltaïques, pompage solaire et optimisation énergétique.",
        'body' => "Ces solutions répondent à une demande croissante en Côte d'Ivoire pour des installations énergétiques fiables et durables, en complément de nos interventions classiques en courants forts et faibles. Notre équipe technique accompagne les projets de la conception à la mise en service.",
        'prev' => 4,
        'next' => 1,
    ],
];
